(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const storeKey='worm-gpt-ultra-v2';
const defaultState={settings:{neon:1,anim:1,particles:90,scan:true,glitch:true,reduced:false,perf:false},sessions:[],active:null};
let state=load(); let startTime=Date.now();
function load(){try{return Object.assign(structuredClone(defaultState),JSON.parse(localStorage.getItem(storeKey)||'{}'))}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function toast(msg,type='info'){const el=document.createElement('div');el.className='toast '+(type==='error'?'error':'');el.textContent=msg;$('#toastHost').append(el);setTimeout(()=>el.remove(),2800)}
function uid(){return 'WG-'+Math.random().toString(36).slice(2,8).toUpperCase()}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nav(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id)); $$('.desktop-nav button,.nav-stack button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id)); history.replaceState(null,'','#'+id); if(id==='status')renderStatus(); if(id==='physics')requestAnimationFrame(drawPhysics); if(id==='math')requestAnimationFrame(drawGraph); if(id==='core3d')requestAnimationFrame(draw3D); closeDrawer('mobileMenu')}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
window.addEventListener('hashchange',()=>nav(location.hash.slice(1)||'home'));

function newSession(){const s={id:uid(),title:'NEW WORM SESSION',created:Date.now(),messages:[]};state.sessions.unshift(s);state.active=s.id;save();renderSessions();renderMessages();addMessage('ai','WORM CORE ONLINE.\nLocal response engine ready. Ask me about physics, mathematics, science, formulas, simulations or type /help.','SYSTEM')}
function activeSession(){return state.sessions.find(s=>s.id===state.active)}
function renderSessions(filter=''){const list=$('#sessionList');list.innerHTML='';const items=state.sessions.filter(s=>s.title.toLowerCase().includes(filter.toLowerCase()));$('#sessionCount').textContent=state.sessions.length;items.forEach(s=>{const d=document.createElement('div');d.className='session-item '+(s.id===state.active?'active':'');d.innerHTML=`<b>${escapeHTML(s.title)}</b><small>${new Date(s.created).toLocaleString()} • ${s.messages.length} msgs</small>`;d.onclick=()=>{state.active=s.id;save();renderSessions();renderMessages()};list.append(d)})}
function renderMessages(){const box=$('#messages');box.innerHTML='';const s=activeSession();if(!s){newSession();return}$('#chatTitle').textContent=s.title; if(!s.messages.length){addMessage('ai','Welcome to WORM GPT.\n\nI am the local scientific response engine. I can simulate structured answers for physics, mathematics, science, formulas, calculations and visual modules.','SYSTEM',false)}else s.messages.forEach(m=>renderMessage(m));box.scrollTop=box.scrollHeight}
function renderMessage(m){const d=document.createElement('div');d.className='msg '+m.role;const time=new Date(m.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});d.innerHTML=`<div class="meta">${m.role==='user'?'YOU':'WORM CORE'} • ${escapeHTML(m.tag||'RESPONSE')} • ${time}</div><div class="bubble">${escapeHTML(m.text)}</div>`;$('#messages').append(d);return d}
function addMessage(role,text,tag='RESPONSE',persist=true){const s=activeSession();if(!s)return;const m={role,text,tag,time:Date.now()};if(persist)s.messages.push(m);renderMessage(m);if(persist){if(role==='user'&&s.messages.length===1){s.title=text.slice(0,30)+(text.length>30?'…':'')}save();renderSessions()}$('#messages').scrollTop=$('#messages').scrollHeight}
function generateResponse(q){const x=q.trim().toLowerCase();
 if(!x)return 'INPUT EMPTY. Enter a question or use /help.';
 if(x==='/help'||x==='help')return 'COMMANDS\n/math — mathematics mode\n/physics — physics lab\n/science — science mode\n/3d — open 3D core\n/system — system diagnostics\n/terminal — safe terminal\n/status — status center\n/clear — clear session\n\nTry: “solve x^2 - 5x + 6”, “calculate 25 * 4”, or “explain gravity”.';
 if(x.startsWith('/math')){nav('math');return 'MATH ENGINE OPENED. Use the calculator, quadratic solver, vector lab or function grapher.'}
 if(x.startsWith('/physics')){nav('physics');return 'PHYSICS ENGINE OPENED. Projectile simulation is ready with live telemetry.'}
 if(x.startsWith('/science')){nav('science');return 'SCIENCE LAB OPENED. Select a domain or ask a scientific question.'}
 if(x.startsWith('/3d')){nav('core3d');return '3D CORE OPENED. Drag the viewport to rotate and use the wheel to zoom.'}
 if(x.startsWith('/system')||x.startsWith('/status')){nav('status');return 'SYSTEM STATUS: ALL LOCAL MODULES READY.'}
 if(x.startsWith('/terminal')){nav('terminal');return 'SAFE TERMINAL OPENED. No real system commands are executed.'}
 if(x.startsWith('/clear')){clearChat();return 'SESSION CLEARED.'}
 const calc=extractCalc(x);if(calc!==null)return `CALCULATION RESULT\n${calc}`;
 const quad=x.match(/x\s*\^?2\s*([+-]\s*\d*\.?\d*)x\s*([+-]\s*\d*\.?\d*)/);if(quad){const b=parseFloat(quad[1].replace(/x/,'')||0),c=parseFloat(quad[2]);const a=1;const d=b*b-4*a*c;if(d>=0){const r1=(-b+Math.sqrt(d))/2,r2=(-b-Math.sqrt(d))/2;return `QUADRATIC SOLUTION\nx₁ = ${fmt(r1)}\nx₂ = ${fmt(r2)}\n\nDiscriminant = ${fmt(d)}`}return 'QUADRATIC SOLUTION\nThe discriminant is negative, so the roots are complex.'}
 if(/hello|hi|hey|مرحبا|اهلا/.test(x))return 'WORM CORE ONLINE. Welcome. Choose a module or ask a scientific question.';
 if(/gravity|جاذبية/.test(x))return 'GRAVITY\nGravity is modeled as an acceleration toward a massive body. Near Earth’s surface, the idealized value is about 9.8 m/s². Use the Physics Engine to explore free fall and projectile motion.';
 if(/relativity|نسبية/.test(x))return 'RELATIVITY\nEinstein’s relativity describes how measurements of space and time depend on relative motion and gravity. Special relativity focuses on inertial motion; general relativity models gravity through spacetime geometry.';
 if(/black hole|ثقب اسود/.test(x))return 'BLACK HOLES\nA black hole is a region where gravity is strong enough that an event horizon forms. The horizon marks a boundary in the classical description; observations of surrounding matter and gravitational waves provide evidence for black-hole systems.';
 if(/quantum|كم/.test(x))return 'QUANTUM CONCEPT\nQuantum mechanics uses probability amplitudes to describe microscopic systems. Superposition and measurement are central concepts, but the local engine presents these as educational summaries rather than a full quantum simulator.';
 if(/wave|موج/.test(x))return 'WAVES\nA wave transfers energy and information through oscillation. Key quantities include amplitude, frequency, wavelength and phase. Open Physics to explore a visual wave model.';
 if(/physics|فيزياء/.test(x))return 'PHYSICS MODE\nAvailable simulations: projectile, free fall, pendulum, orbit and wave. Open the Physics Engine for interactive telemetry.';
 if(/math|رياضيات|formula|معادلة/.test(x))return 'MATH MODE\nUse the calculator, quadratic solver, vectors and function grapher. You can also enter expressions such as 25 * 4 or solve x^2 - 5x + 6.';
 if(/3d|three d|ثلاث/.test(x)){nav('core3d');return '3D CORE READY. Particle field, sphere, cube and orbit visualizations are available.'}
 if(/science|علم/.test(x))return 'SCIENCE LAB\nExplore mechanics, astronomy, waves, thermodynamics, engineering and quantum concepts.';
 return `LOCAL RESPONSE ENGINE\nI parsed your request as: “${q}”\n\nI can currently provide structured local summaries for science, physics, mathematics, formulas, calculations and visual simulations. Try /help for commands.`;
}
function extractCalc(x){if(!/^(calculate|calc|what is|احسب)\b/.test(x))return null;let e=x.replace(/^(calculate|calc|what is|احسب)\s*/,'').replace(/×/g,'*').replace(/÷/g,'/').replace(/\^/g,'**');if(!/^[0-9+\-*/().\s%**sqrtincosta]+$/i.test(e))return null;try{const safe=e.replace(/sqrt/gi,'Math.sqrt').replace(/sin/gi,'Math.sin').replace(/cos/gi,'Math.cos').replace(/tan/gi,'Math.tan');const r=Function('"use strict";return ('+safe+')')();return Number.isFinite(r)?fmt(r):null}catch{return null}}
function fmt(n){return Math.abs(n)<1e-10?'0':Number(n.toFixed(6)).toString()}
async function send(text){text=text.trim().slice(0,1000);if(!text)return;addMessage('user',text,'QUERY');const d=document.createElement('div');d.className='msg ai';d.innerHTML='<div class="meta">WORM CORE • ANALYZING...</div><div class="bubble">SCANNING LOCAL KNOWLEDGE...<br>BUILDING RESPONSE...</div>';$('#messages').append(d);$('#messages').scrollTop=$('#messages').scrollHeight;await new Promise(r=>setTimeout(r,Math.min(900,350+text.length*8)));d.remove();const resp=generateResponse(text);addMessage('ai',resp,'RESPONSE');save();renderSessions()}
$('#sendChat').onclick=()=>{const i=$('#chatInput');send(i.value);i.value='';$('#charCount').textContent='0 / 1000'};
$('#chatInput').addEventListener('input',e=>{e.target.value=e.target.value.slice(0,1000);$('#charCount').textContent=`${e.target.value.length} / 1000`;e.target.style.height='auto';e.target.style.height=Math.min(130,e.target.scrollHeight)+'px'});
$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#sendChat').click()}});
$$('.quick-prompts button,.sciencePrompt').forEach(b=>b.addEventListener('click',()=>send(b.dataset.prompt)));
$$('.composer-tools button').forEach(b=>b.onclick=()=>{$('#chatInput').value=b.dataset.command;$('#sendChat').click()});
$('#newChat').onclick=newSession;$('#newSessionTop').onclick=newSession;$('#clearChat').onclick=clearChat;$('#clearAllChats').onclick=()=>{if(confirm('Clear all local sessions?')){state.sessions=[];state.active=null;save();newSession()}};$('#chatSearch').oninput=e=>renderSessions(e.target.value);$('#focusMode').onclick=()=>document.body.classList.toggle('focus-mode');$('#fullscreenChat').onclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});
function clearChat(){const s=activeSession();if(!s)return;s.messages=[];save();renderMessages();toast('Session cleared','info')}
$('#exportChat').onclick=()=>{const blob=new Blob([JSON.stringify(activeSession(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='worm-gpt-session.json';a.click();URL.revokeObjectURL(a.href);toast('Session exported')}

// physics
const pc=$('#physicsCanvas'),pctx=pc.getContext('2d');let physRunning=false,physT=0,lastP=0;
function physVals(){return {v:+$('#physVelocity').value,a:+$('#physAngle').value*Math.PI/180,g:+$('#physGravity').value,m:+$('#physMass').value,s:+$('#physSpeed').value}}
function updatePhysUI(){const z=physVals(),vx=z.v*Math.cos(z.a),vy=z.v*Math.sin(z.a),T=2*vy/z.g,R=vx*T,H=vy*vy/(2*z.g),E=.5*z.m*z.v*z.v;$('#velOut').value=z.v;$('#angleOut').value=Math.round(z.a*180/Math.PI);$('#gravOut').value=z.g;$('#massOut').value=z.m;$('#speedOut').value=z.s+'×';$('#rangeOut').textContent=fmt(R);$('#heightOut').textContent=fmt(H);$('#timeOut').textContent=fmt(T);$('#energyOut').textContent=fmt(E);$('#vxOut').textContent=fmt(vx);$('#vyOut').textContent=fmt(vy)}
function drawPhysics(ts=0){const w=pc.width,h=pc.height,z=physVals();pctx.clearRect(0,0,w,h);pctx.fillStyle='#03060a';pctx.fillRect(0,0,w,h);pctx.strokeStyle='rgba(0,183,255,.09)';pctx.lineWidth=1;for(let x=0;x<w;x+=45){pctx.beginPath();pctx.moveTo(x,0);pctx.lineTo(x,h);pctx.stroke()}for(let y=0;y<h;y+=45){pctx.beginPath();pctx.moveTo(0,y);pctx.lineTo(w,y);pctx.stroke()}const T=2*z.v*Math.sin(z.a)/z.g,R=z.v*z.v*Math.sin(2*z.a)/z.g,H=z.v*z.v*Math.sin(z.a)**2/(2*z.g);const scale=Math.min((w-90)/(R||1),(h-90)/(H||1)*.8);const ground=h-35;const ox=35; pctx.strokeStyle='rgba(255,255,255,.2)';pctx.beginPath();pctx.moveTo(0,ground);pctx.lineTo(w,ground);pctx.stroke();pctx.strokeStyle='rgba(0,183,255,.6)';pctx.lineWidth=2;pctx.beginPath();for(let i=0;i<=100;i++){const t=T*i/100,x=z.v*Math.cos(z.a)*t,y=z.v*Math.sin(z.a)*t-.5*z.g*t*t;const px=ox+x*scale,py=ground-y*scale;i?pctx.lineTo(px,py):pctx.moveTo(px,py)}pctx.stroke();const t=Math.min(physT,T),x=z.v*Math.cos(z.a)*t,y=z.v*Math.sin(z.a)*t-.5*z.g*t*t;const px=ox+x*scale,py=ground-y*scale;pctx.fillStyle='#ff1744';pctx.shadowBlur=18;pctx.shadowColor='#ff1744';pctx.beginPath();pctx.arc(px,py,7,0,Math.PI*2);pctx.fill();pctx.shadowBlur=0;pctx.fillStyle='#789';pctx.font='11px monospace';pctx.fillText(`t=${fmt(t)}s`,12,20);if(physRunning){physT+=((ts-lastP)/1000)*z.s; if(physT>=T){physT=0}lastP=ts;requestAnimationFrame(drawPhysics)}}
['physVelocity','physAngle','physGravity','physMass','physSpeed'].forEach(id=>$('#'+id).addEventListener('input',()=>{updatePhysUI();if(!physRunning)drawPhysics()}));$('#physPlay').onclick=()=>{physRunning=true;$('#physState').textContent='RUNNING';lastP=performance.now();requestAnimationFrame(drawPhysics)};$('#physPause').onclick=()=>{physRunning=false;$('#physState').textContent='PAUSED'};$('#physReset').onclick=()=>{physRunning=false;physT=0;$('#physState').textContent='READY';updatePhysUI();drawPhysics()};$$('.sim-tabs button').forEach(b=>b.onclick=()=>{ $$('.sim-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent} model selected`) });updatePhysUI();drawPhysics();

// math
function calcEval(){let e=$('#calcInput').value.replace(/×/g,'*').replace(/÷/g,'/').replace(/\^/g,'**').replace(/sqrt/gi,'Math.sqrt').replace(/sin/gi,'Math.sin').replace(/cos/gi,'Math.cos').replace(/tan/gi,'Math.tan');if(!/^[0-9+\-*/().\s*Math.sincotqru]+$/i.test(e))throw Error('Invalid expression');return Function('"use strict";return ('+e+')')()}
$$('[data-calc]').forEach(b=>b.onclick=()=>{$('#calcInput').value+=b.dataset.calc});$('#calcEquals').onclick=()=>{try{$('#calcResult').textContent=fmt(calcEval())}catch{$('#calcResult').textContent='INVALID EXPRESSION'}};
$('#solveQuadratic').onclick=()=>{const a=+$('#qa').value,b=+$('#qb').value,c=+$('#qc').value,d=b*b-4*a*c;if(!a){$('#quadResult').textContent='a must not be 0';return}if(d<0){$('#quadResult').textContent=`Complex roots • Δ = ${fmt(d)}`;return}$('#quadResult').textContent=`x₁ = ${fmt((-b+Math.sqrt(d))/(2*a))} • x₂ = ${fmt((-b-Math.sqrt(d))/(2*a))}`};
const gc=$('#graphCanvas'),gctx=gc.getContext('2d');function graphFn(x,expr){let e=expr.toLowerCase().replace(/\^/g,'**').replace(/sin/g,'Math.sin').replace(/cos/g,'Math.cos').replace(/tan/g,'Math.tan').replace(/sqrt/g,'Math.sqrt').replace(/log/g,'Math.log');if(!/^[0-9x+\-*/().\s*Math.sincotaqrt]+$/i.test(e))throw Error('bad');return Function('x','"use strict";return '+e)(x)}function drawGraph(){const w=gc.width,h=gc.height;gctx.fillStyle='#03060a';gctx.fillRect(0,0,w,h);gctx.strokeStyle='rgba(0,183,255,.08)';for(let x=0;x<w;x+=45){gctx.beginPath();gctx.moveTo(x,0);gctx.lineTo(x,h);gctx.stroke()}for(let y=0;y<h;y+=45){gctx.beginPath();gctx.moveTo(0,y);gctx.lineTo(w,y);gctx.stroke()}gctx.strokeStyle='rgba(255,255,255,.2)';gctx.beginPath();gctx.moveTo(w/2,0);gctx.lineTo(w/2,h);gctx.moveTo(0,h/2);gctx.lineTo(w,h/2);gctx.stroke();let expr=$('#graphExpr').value;gctx.strokeStyle='#00d9ff';gctx.lineWidth=2;gctx.beginPath();for(let i=0;i<w;i++){const x=(i-w/2)/35;let y;try{y=graphFn(x,expr)}catch{return}if(!Number.isFinite(y)){continue}const py=h/2-y*35;i?gctx.lineTo(i,py):gctx.moveTo(i,py)}gctx.stroke()}$('#plotGraph').onclick=drawGraph;$('#resetGraph').onclick=()=>{$('#graphExpr').value='sin(x)';drawGraph()};drawGraph();
$('#vectorCalc').onclick=()=>{const a=[+$(`#vax`).value,+$(`#vay`).value,+$(`#vaz`).value],b=[+$(`#vbx`).value,+$(`#vby`).value,+$(`#vbz`).value];const dot=a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];$('#vectorResult').textContent=`DOT: ${fmt(dot)} • CROSS: [${cross.map(fmt).join(', ')}]`};
const formulas=[['F = m × a','Newton’s second law'],['E = m c²','Mass–energy equivalence'],['v = Δx / Δt','Average velocity'],['K = ½mv²','Kinetic energy'],['p = mv','Momentum'],['V = IR','Ohm’s law'],['P = W / t','Power'],['ρ = m / V','Density']];$('#formulaGrid').innerHTML=formulas.map(f=>`<article class="formula-card"><strong>${f[0]}</strong><span>${f[1]}</span></article>`).join('');$('#formulaRandom').onclick=()=>{const f=formulas[Math.floor(Math.random()*formulas.length)];toast(`${f[0]} — ${f[1]}`)};

// 3D canvas
const c3=$('#coreCanvas'),x3=c3.getContext('2d');let rot=0,zoom=1,drag=false,lastX=0,particles=[];function seedParticles(){particles=Array.from({length:+state.settings.particles||90},()=>({x:Math.random()*2-1,y:Math.random()*2-1,z:Math.random()*2-1,s:Math.random()*2+.5}))};seedParticles();function project(p){const c=Math.cos(rot),s=Math.sin(rot),x=p.x*c-p.z*s,z=p.x*s+p.z*c;const d=2.7+z,scale=150*zoom/d;return{x:c3.width/2+x*scale,y:c3.height/2+p.y*scale,d}}function draw3D(){const w=c3.width,h=c3.height;x3.fillStyle='#02050a';x3.fillRect(0,0,w,h);x3.strokeStyle='rgba(0,183,255,.08)';for(let x=0;x<w;x+=55){x3.beginPath();x3.moveTo(x,0);x3.lineTo(x,h);x3.stroke()}for(let y=0;y<h;y+=55){x3.beginPath();x3.moveTo(0,y);x3.lineTo(w,y);x3.stroke()}const type=$('#objectType').value;$('#objectLabel').textContent=type.toUpperCase();if(type==='particles'){particles.forEach(p=>{p.z+=.004;if(p.z>1)p.z=-1;const q=project(p);x3.fillStyle=`rgba(0,210,255,${Math.max(.15,1-q.d/4)})`;x3.beginPath();x3.arc(q.x,q.y,Math.max(1,3/q.d),0,Math.PI*2);x3.fill()})}else if(type==='sphere'){for(let i=0;i<70;i++){const a=i/70*Math.PI*2,q=project({x:Math.cos(a)*.9,y:Math.sin(a)*.9,z:0});x3.strokeStyle=i%2?'rgba(0,183,255,.2)':'rgba(255,23,68,.18)';x3.beginPath();x3.arc(q.x,q.y,90,0,Math.PI*2);x3.stroke()}}else if(type==='cube'){const pts=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(([x,y,z])=>project({x:x*.7,y:y*.7,z:z*.7}));const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];x3.strokeStyle='rgba(0,210,255,.75)';x3.lineWidth=2;edges.forEach(e=>{x3.beginPath();x3.moveTo(pts[e[0]].x,pts[e[0]].y);x3.lineTo(pts[e[1]].x,pts[e[1]].y);x3.stroke()})}else{for(let r=1;r<4;r++){x3.strokeStyle=`rgba(255,23,68,${.18/r})`;x3.beginPath();x3.ellipse(w/2,h/2,90*r,35*r,rot*.4,0,Math.PI*2);x3.stroke()}}if($('#autoRotate').checked)rot+=.006*(+$('#rotation3d').value||.7);requestAnimationFrame(draw3D)}$('#rotation3d').oninput=()=>{};$('#zoom3d').oninput=e=>{zoom=+e.target.value};$('#objectType').onchange=()=>{$('#particleCount').textContent=particles.length};$('#reset3d').onclick=()=>{rot=0;zoom=1;$('#zoom3d').value=1};c3.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;c3.setPointerCapture(e.pointerId)});c3.addEventListener('pointerup',()=>drag=false);c3.addEventListener('pointermove',e=>{if(drag){rot+=(e.clientX-lastX)*.01;lastX=e.clientX}});c3.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom-e.deltaY*.001));$('#zoom3d').value=zoom},{passive:false});draw3D();

// terminal
const termOut=$('#terminalOutput');function term(line,cls=''){const d=document.createElement('div');d.className='term-line '+cls;d.textContent=line;termOut.append(d);termOut.scrollTop=termOut.scrollHeight}function runTerm(raw){const c=raw.trim().toLowerCase();if(!c)return;if(c==='clear'){termOut.innerHTML='';return}if(c==='help'){['WORM SAFE TERMINAL','help       list commands','status     system status','diagnostics run self-check','physics    open physics engine','math       open math engine','science    open science lab','clear      clear output','version    show version'].forEach((x,i)=>term(x,i===0?'red':''));return}if(c==='status'){term('CORE: ONLINE');term('AI: LOCAL RESPONSE ENGINE');term('PHYSICS: READY');term('MATH: READY');term('3D: READY');return}if(c==='diagnostics'){term('RUNNING SAFE DIAGNOSTICS...');['HTML: OK','CSS: OK','JAVASCRIPT: OK','LOCAL STORAGE: '+(typeof localStorage!=='undefined'?'OK':'UNAVAILABLE'),'CANVAS: '+(pc?'OK':'UNAVAILABLE'),'NETWORK: NOT REQUIRED'].forEach(x=>term(x));term('DIAGNOSTICS COMPLETE','red');return}if(c==='physics'){nav('physics');term('PHYSICS ENGINE OPENED.');return}if(c==='math'){nav('math');term('MATH ENGINE OPENED.');return}if(c==='science'){nav('science');term('SCIENCE LAB OPENED.');return}if(c==='version'){term('WORM GPT ULTRA CYBER SCIENCE v2.0.0');return}term('UNKNOWN COMMAND — TYPE help','red')};['WORM SAFE TERMINAL // LOCAL SIMULATION','Type help to begin.','No real system commands are executed.'].forEach((x,i)=>term(x,i===0?'red':''));$('#terminalRun').onclick=()=>{const i=$('#terminalInput');term('> '+i.value,'gray');runTerm(i.value);i.value=''};$('#terminalInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#terminalRun').click()});$$('[data-terminal]').forEach(b=>b.onclick=()=>{term('> '+b.dataset.terminal,'gray');runTerm(b.dataset.terminal)});

// status
const modules=[['AI CORE','Local response engine'],['PHYSICS ENGINE','Canvas simulation'],['MATH ENGINE','Calculator + grapher'],['3D CORE','Canvas visualizer'],['STORAGE','Browser localStorage'],['RENDER','Browser rendering'],['TERMINAL','Safe emulator'],['UI SYSTEM','Responsive HUD']];function renderStatus(){$('#statusGrid').innerHTML=modules.map(m=>`<article class="status-card"><i class="pulse"></i><span class="state">● ONLINE</span><h3>${m[0]}</h3><p>${m[1]}</p></article>`).join('')};renderStatus();setInterval(()=>{$('#systemTime').textContent=new Date().toLocaleTimeString();const up=Math.floor((Date.now()-startTime)/1000);$('#uptime').textContent=`UPTIME ${String(Math.floor(up/60)).padStart(2,'0')}:${String(up%60).padStart(2,'0')}`;$('#renderBar').style.setProperty('--w',(35+Math.random()*35)+'%');$('#memoryBar').style.setProperty('--w',(45+Math.random()*30)+'%');$('#simBar').style.setProperty('--w',(20+Math.random()*50)+'%')},1000);

// settings
function applySettings(){const s=state.settings;document.documentElement.style.setProperty('--glow',s.neon);document.documentElement.style.setProperty('--anim',s.anim);document.documentElement.style.setProperty('--glow',s.neon);document.body.classList.toggle('performance',s.perf);$('.scanlines').style.display=s.scan?'block':'none';$$('.glitch').forEach(e=>e.style.visibility=s.glitch?'visible':'visible');$('#setNeon').value=s.neon;$('#setAnim').value=s.anim;$('#setParticles').value=s.particles;$('#setScan').checked=s.scan;$('#setGlitch').checked=s.glitch;$('#setReduced').checked=s.reduced;$('#setPerf').checked=s.perf;particles.length!==s.particles&&seedParticles();if(s.reduced)document.documentElement.classList.add('reduced');else document.documentElement.classList.remove('reduced')}
[['setNeon','neon','input'],['setAnim','anim','input'],['setParticles','particles','input'],['setScan','scan','change'],['setGlitch','glitch','change'],['setReduced','reduced','change'],['setPerf','perf','change']].forEach(([id,key,ev])=>$('#'+id).addEventListener(ev,e=>{state.settings[key]=e.target.type==='checkbox'?e.target.checked:+e.target.value;save();applySettings()}));$('#resetSettings').onclick=()=>{state.settings=structuredClone(defaultState.settings);save();applySettings();toast('Settings reset')};applySettings();
function openDrawer(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}function closeDrawer(id){$('#'+id)?.classList.remove('open');$('#'+id)?.setAttribute('aria-hidden','true')}$('#openSettings').onclick=()=>openDrawer('settings');$('#openMenu').onclick=()=>openDrawer('mobileMenu');$$('[data-close]').forEach(b=>b.onclick=()=>closeDrawer(b.dataset.close));

// command palette
const commands=[['New Session','Create a new AI session','new'],['AI Chat','Open AI interface','chat'],['Science Lab','Open science modules','science'],['Physics Engine','Open physics simulation','physics'],['Math Engine','Open math tools','math'],['3D Core','Open 3D visualizer','core3d'],['Terminal','Open safe terminal','terminal'],['Status Center','Open system status','status'],['Settings','Open system settings','settings']];function renderCmd(filter=''){const list=$('#cmdList');list.innerHTML='';commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(filter.toLowerCase())).forEach(c=>{const d=document.createElement('div');d.className='cmd';d.innerHTML=`<b>${c[0]}</b><span>${c[1]}</span>`;d.onclick=()=>{if(c[2]==='new')newSession();else if(c[2]==='settings')openDrawer('settings');else nav(c[2]);closeCmd()};list.append(d)})}function openCmd(){renderCmd();$('#commandPalette').classList.add('open');$('#cmdInput').value='';$('#cmdInput').focus()}function closeCmd(){$('#commandPalette').classList.remove('open')}$('#openCmd').onclick=openCmd;$('#cmdInput').oninput=e=>renderCmd(e.target.value);$('#cmdInput').onkeydown=e=>{if(e.key==='Enter')$('#cmdList .cmd')?.click();if(e.key==='Escape')closeCmd()};$('#commandPalette').onclick=e=>{if(e.target.id==='commandPalette')closeCmd()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCmd()}if(e.key==='Escape')closeCmd()});

// background particles
const bg=$('#bgCanvas'),bc=bg.getContext('2d');let bp=[];function resizeBg(){bg.width=innerWidth*devicePixelRatio;bg.height=innerHeight*devicePixelRatio;bc.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);seedBg()}function seedBg(){const n=state.settings.perf?0:state.settings.particles;bp=Array.from({length:n},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,r:Math.random()*1.6+.3}))}function drawBg(){bc.clearRect(0,0,innerWidth,innerHeight);for(const p of bp){p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;bc.fillStyle=Math.random()>.5?'rgba(0,183,255,.35)':'rgba(255,23,68,.3)';bc.beginPath();bc.arc(p.x,p.y,p.r,0,Math.PI*2);bc.fill()}requestAnimationFrame(drawBg)}addEventListener('resize',resizeBg);resizeBg();drawBg();

// boot
function boot(){const b=$('#bootBar'),t=$('#bootText'),screen=$('#boot');let i=0;const lines=['INITIALIZING WORM CORE...','LOADING LOCAL RESPONSE ENGINE...','CALIBRATING PHYSICS ENGINE...','MOUNTING MATH ENGINE...','INITIALIZING 3D CORE...','RUNNING SAFE DIAGNOSTICS...','SYSTEM READY.'];const timer=setInterval(()=>{i++;b.style.width=(i/(lines.length-1)*100)+'%';t.textContent=lines[Math.min(i,lines.length-1)];if(i>=lines.length-1){clearInterval(timer);setTimeout(()=>screen.classList.add('hidden'),450)}},180);$('#skipBoot').onclick=()=>{clearInterval(timer);screen.classList.add('hidden')}}boot();
if(!state.sessions.length)newSession();else{renderSessions();renderMessages()}
nav(location.hash.slice(1)||'home');
})();
